environment = "prod"
location    = "East US"
resource_group_name = "myproject-prod-rg"
database_name       = "myproject-prod-db"
database_username   = "myprojectuser"
database_password   = "P@ssw0rd123!"
