environment = "staging"
location    = "West US"
resource_group_name = "myproject-staging-rg"
database_name       = "myproject-staging-db"
database_username   = "myprojectuser"
database_password   = "P@ssw0rd123!"
