name: Code Review and IaC with AI
on: [push]

jobs:
  ai-review-job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4.0.0

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install Python dependencies
          run: pip install ollama

        - name: Install and Setup Ollama
          run: |
            curl -fsSL https://ollama.com/install.sh | sh
            ollama serve &
            sleep 5
            ollama pull llama3.1

        - name: Run AI code review
          run: python ai_reviewer.py

  # Job 2: Setup IaC
  terraform-plan:
      needs: ai-review-job
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.0.0
        - name: Login on Azure
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init e Plan
          run: |
              terraform init
              terraform plan
            

  # Job 3: Apply IaC
  terraform-apply:
      needs: terraform-plan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.0.0
        - name: Login on Azure
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Apply
          run: |
              terraform init
              terraform apply -auto-approve